services:
  nginx:
    build: ./nginx
    container_name: aquaweb-nginx
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types
    ports:
      - "4000:4000"
  php:
    build: ./php-server
    container_name: aquaweb-php
    volumes:
      - ./:/usr/share/nginx/html
    expose:
      - 9000
  db:
    image: mysql
    container_name: aquaweb-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db-data:/var/lib/mysql
      - ./aquaweb.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_DATABASE=aquaweb
      - MYSQL_ROOT_PASSWORD=webaqua123
    expose:
      - 3306
volumes:
  db-data:
